import type { Metadata } from 'next'
import { Averia_Serif_Libre, Amiri } from 'next/font/google'
import './globals.css'

import Header from '@/app/components/Header'
import Footer from '@/app/components/Footer'
import WelcomeMessage from '@/app/components/WelcomeMessage'

const averiaSerifLibre = Averia_Serif_Libre({
  variable: '--font-averia-serif-libre',
  subsets: ['latin'],
  weight: ['300', '400', '700'],
})

const amiri = Amiri({
  variable: '--font-amiri',
  subsets: ['latin'],
  weight: ['400', '700'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${averiaSerifLibre.variable} ${amiri.variable} antialiased bg-background`}
      >
        <Header />
        <main className="pt-[98px] pb-[150px]">
          <WelcomeMessage />
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
